version: "3"

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mymongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mymongo-data:/data/db

volumes:
  mymongo-data:
